// Code generated by mockery v2.22.1. DO NOT EDIT.

package mocks

import (
	model "vod/model"

	mock "github.com/stretchr/testify/mock"
)

// RedisRepository is an autogenerated mock type for the RedisRepository type
type RedisRepository struct {
	mock.Mock
}

// GetFromRedis provides a mock function with given fields: videoMD
func (_m *RedisRepository) GetFromRedis(videoMD model.VideoMetaData) (model.VideoMetaData, error) {
	ret := _m.Called(videoMD)

	var r0 model.VideoMetaData
	var r1 error
	if rf, ok := ret.Get(0).(func(model.VideoMetaData) (model.VideoMetaData, error)); ok {
		return rf(videoMD)
	}
	if rf, ok := ret.Get(0).(func(model.VideoMetaData) model.VideoMetaData); ok {
		r0 = rf(videoMD)
	} else {
		r0 = ret.Get(0).(model.VideoMetaData)
	}

	if rf, ok := ret.Get(1).(func(model.VideoMetaData) error); ok {
		r1 = rf(videoMD)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetInRedis provides a mock function with given fields: _a0
func (_m *RedisRepository) SetInRedis(_a0 model.VideoMetaData) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(model.VideoMetaData) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewRedisRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewRedisRepository creates a new instance of RedisRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRedisRepository(t mockConstructorTestingTNewRedisRepository) *RedisRepository {
	mock := &RedisRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
