// Code generated by mockery v2.22.1. DO NOT EDIT.

package mocks

import (
	model "vod/model"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Find provides a mock function with given fields: videoMDToPlay
func (_m *Repository) Find(videoMDToPlay model.VideoMetaData) (model.VideoMetaData, error) {
	ret := _m.Called(videoMDToPlay)

	var r0 model.VideoMetaData
	var r1 error
	if rf, ok := ret.Get(0).(func(model.VideoMetaData) (model.VideoMetaData, error)); ok {
		return rf(videoMDToPlay)
	}
	if rf, ok := ret.Get(0).(func(model.VideoMetaData) model.VideoMetaData); ok {
		r0 = rf(videoMDToPlay)
	} else {
		r0 = ret.Get(0).(model.VideoMetaData)
	}

	if rf, ok := ret.Get(1).(func(model.VideoMetaData) error); ok {
		r1 = rf(videoMDToPlay)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepository(t mockConstructorTestingTNewRepository) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
