// Code generated by mockery v2.22.1. DO NOT EDIT.

package mocks

import (
	model "vod/model"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Find provides a mock function with given fields: videoID
func (_m *Repository) Find(videoID int) (model.VideoMetaData, error) {
	ret := _m.Called(videoID)

	var r0 model.VideoMetaData
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (model.VideoMetaData, error)); ok {
		return rf(videoID)
	}
	if rf, ok := ret.Get(0).(func(int) model.VideoMetaData); ok {
		r0 = rf(videoID)
	} else {
		r0 = ret.Get(0).(model.VideoMetaData)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(videoID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: encodeToEncrypt
func (_m *Repository) Update(encodeToEncrypt map[model.VideoLinks]model.VideoLinks) (bool, error) {
	ret := _m.Called(encodeToEncrypt)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(map[model.VideoLinks]model.VideoLinks) (bool, error)); ok {
		return rf(encodeToEncrypt)
	}
	if rf, ok := ret.Get(0).(func(map[model.VideoLinks]model.VideoLinks) bool); ok {
		r0 = rf(encodeToEncrypt)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(map[model.VideoLinks]model.VideoLinks) error); ok {
		r1 = rf(encodeToEncrypt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepository(t mockConstructorTestingTNewRepository) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
