// Code generated by mockery v2.22.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IToken is an autogenerated mock type for the IToken type
type IToken struct {
	mock.Mock
}

// GenerateToken provides a mock function with given fields:
func (_m *IToken) GenerateToken() (string, error) {
	ret := _m.Called()

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewIToken interface {
	mock.TestingT
	Cleanup(func())
}

// NewIToken creates a new instance of IToken. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIToken(t mockConstructorTestingTNewIToken) *IToken {
	mock := &IToken{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
