// Code generated by mockery v2.22.1. DO NOT EDIT.

package mocks

import (
	model "vod/model"

	mock "github.com/stretchr/testify/mock"
)

// RedisRepository is an autogenerated mock type for the RedisRepository type
type RedisRepository struct {
	mock.Mock
}

// GetFromRedis provides a mock function with given fields: user
func (_m *RedisRepository) GetFromRedis(user model.User) (model.User, error) {
	ret := _m.Called(user)

	var r0 model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(model.User) (model.User, error)); ok {
		return rf(user)
	}
	if rf, ok := ret.Get(0).(func(model.User) model.User); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Get(0).(model.User)
	}

	if rf, ok := ret.Get(1).(func(model.User) error); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetInRedis provides a mock function with given fields: user, token
func (_m *RedisRepository) SetInRedis(user model.User, token string) error {
	ret := _m.Called(user, token)

	var r0 error
	if rf, ok := ret.Get(0).(func(model.User, string) error); ok {
		r0 = rf(user, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewRedisRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewRedisRepository creates a new instance of RedisRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRedisRepository(t mockConstructorTestingTNewRedisRepository) *RedisRepository {
	mock := &RedisRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
