// Code generated by mockery v2.22.1. DO NOT EDIT.

package mocks

import (
	model "vod/model"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Create provides a mock function with given fields: videoLinks, videoId
func (_m *Repository) Create(videoLinks []string, videoId string) ([]model.VideoLinks, model.VideoMetaData, error) {
	ret := _m.Called(videoLinks, videoId)

	var r0 []model.VideoLinks
	var r1 model.VideoMetaData
	var r2 error
	if rf, ok := ret.Get(0).(func([]string, string) ([]model.VideoLinks, model.VideoMetaData, error)); ok {
		return rf(videoLinks, videoId)
	}
	if rf, ok := ret.Get(0).(func([]string, string) []model.VideoLinks); ok {
		r0 = rf(videoLinks, videoId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.VideoLinks)
		}
	}

	if rf, ok := ret.Get(1).(func([]string, string) model.VideoMetaData); ok {
		r1 = rf(videoLinks, videoId)
	} else {
		r1 = ret.Get(1).(model.VideoMetaData)
	}

	if rf, ok := ret.Get(2).(func([]string, string) error); ok {
		r2 = rf(videoLinks, videoId)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

type mockConstructorTestingTNewRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepository(t mockConstructorTestingTNewRepository) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
